docs_dir: wiki
site_name: PSForever Wiki
site_url: https://psforever.github.io/wiki/
repo_url: https://github.com/psforever/wiki
repo_name: GitHub
edit_uri: blob/main/wiki/
theme:
  name: material
  logo: res/logo.png
  favicon: res/favicon.png
  palette:
    primary: black
  features:
    - navigation.indexes
    - navigation.instant
markdown_extensions:
  - attr_list
  - md_in_html
  - figure
  - toc:
      toc_depth: "1-4"
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/0nRe5TNbTYoUruA4
    - icon: fontawesome/brands/github
      link: https://github.com/psforever
extra_javascript:
  - https://unpkg.com/jquery@3/dist/jquery.min.js
  - https://unpkg.com/featherlight@1/release/featherlight.min.js
extra_css:
  - https://unpkg.com/featherlight@1/release/featherlight.min.css
  - res/figure.css
